touch \
src/app.ts \
src/server.ts \
src/config/env.ts \
src/config/db.ts \
src/config/logger.ts \
src/config/socket.ts \
src/modules/auth/auth.controller.ts \
src/modules/auth/auth.service.ts \
src/modules/auth/auth.routes.ts \
src/modules/auth/auth.validation.ts \
src/modules/users/user.model.ts \
src/modules/users/user.controller.ts \
src/modules/users/user.service.ts \
src/modules/users/user.routes.ts \
src/modules/users/user.validation.ts \
src/modules/requests/request.model.ts \
src/modules/requests/request.controller.ts \
src/modules/requests/request.service.ts \
src/modules/requests/request.routes.ts \
src/modules/requests/request.validation.ts \
src/modules/donations/donation.model.ts \
src/modules/donations/donation.service.ts \
src/modules/donations/donation.routes.ts \
src/modules/notifications/notification.model.ts \
src/modules/notifications/notification.service.ts \
src/modules/notifications/notification.routes.ts \
src/middlewares/auth.middleware.ts \
src/middlewares/role.middleware.ts \
src/middlewares/error.middleware.ts \
src/middlewares/rateLimiter.middleware.ts \
src/middlewares/validate.middleware.ts \
src/sockets/socketManager.ts \
src/sockets/events.ts \
src/utils/haversine.ts \
src/utils/generateTokens.ts \
src/utils/constants.ts
